# This workflow runs tests and other checks on Pull Requests and merges to main.
name: Checks

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test-cov:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Test Coverage
        run: |
            uv run --python ${{ matrix.python-version }} pytest
